-- Count the rows currently loaded in each table.

SELECT 'BRANCH' AS table_name, COUNT(*) AS row_count FROM BRANCH
UNION ALL
SELECT 'EMPLOYEE', COUNT(*) FROM EMPLOYEE
UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM CUSTOMER
UNION ALL
SELECT 'MENU_ITEM', COUNT(*) FROM MENU_ITEM
UNION ALL
SELECT 'INGREDIENT', COUNT(*) FROM INGREDIENT
UNION ALL
SELECT 'REWARD', COUNT(*) FROM REWARD
UNION ALL
SELECT 'PIZZA_ORDER', COUNT(*) FROM PIZZA_ORDER
UNION ALL
SELECT 'ORDER_ITEM', COUNT(*) FROM ORDER_ITEM
UNION ALL
SELECT 'RECIPE', COUNT(*) FROM RECIPE
UNION ALL
SELECT 'INVENTORY', COUNT(*) FROM INVENTORY
UNION ALL
SELECT 'INSPECTION', COUNT(*) FROM INSPECTION
ORDER BY table_name;
